version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5680:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=worldwise

    volumes:
      - worldwise_pg_data:/bitnami/postgresql

volumes:
  worldwise_pg_data:
